### ISSUE TITLE
Plugin installation error in macOS High Sierra - Intellij IDEA 2017 

### ISSUE THREAD

**Issue by ksdperera** [wso2/siddhi-plugin-idea#4]
**Description:**
There is plugin installation error in following environment. As per the message I have checked whether there is mentioned directory but couldn't find the directory and Siddhi-IntelliJ-Plugin.zip.

Error Message:
<img width="866" alt="screen shot 2017-12-17 at 9 55 29 pm" src="https://user-images.githubusercontent.com/5366557/34081765-44641e62-e378-11e7-8223-29159d7115a3.png">

```
Most probably, this happened because of a change in a serialization format.
Please try again, and if the problem persists, please report it
to http://jb.gg/ide/critical-startup-errors

The cause: Source file missing: /Users/sajithd/Library/Caches/IntelliJIdea2017.3/plugins/Siddhi-IntelliJ-Plugin.zip
```
**Affected Product Version:**
v1.0.0

**OS, DB, other environment details and versions:**    
macOS High Sierra v10.13.1
Intellij IDEA 2017.3
**Steps to reproduce:**

1. Install the plugin
2. After install restart the Intellij IDEA

**Comment by RAVEENSR** [comment]
Will look into this

**Comment by RAVEENSR** [comment]
Please follow these steps and you will be able to install the plugin.

Go to Preferences in MacOS-> Plugins.
Select Browse Repositories button at the bottom.
Search for Siddhi using the search box. Siddhi plugin will show up. Then you can install the plugin using the Install button.
Restart IDEA.

PS: The issue occurred because you tried to install siddhi plugin through the popup message link which appears when detected a .siddhi file type. This issue is related to Intellij IDEA itself. You can install plugin successfully by following the above steps.

**Comment by ksdperera** [comment]
Thanks Raween !
I was able to install the plugin with the above provided steps.
If it is know issue, may be we can add it as note in the documentation or in reference blog.

**Comment by suhothayan** [comment]
Please add how to install also as a section on the docs.

**Comment by RAVEENSR** [comment]
Fixed in the doc. It is available under Setup the Siddhi plugin for Intellij IDEA and Siddhi SDK. 
https://wso2.github.io/siddhi-plugin-idea/
